version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: spug-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/:/var/lib/mysql/
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: spug
      MYSQL_DATABASE: spug
      MYSQL_USER: spug
      MYSQL_PASSWORD: spug
    networks:
      - spug
  redis:
    image: redis:5-alpine
    container_name: spug-redis
    volumes:
      - ./redis/:/data/
    restart: always
    ports:
      - "6379:6379"
    networks:
      - spug
  spug:
    image: hyr326/spug:latest
    container_name: spug
    depends_on: 
      - mysql
      - redis
    restart: on-failure
    ports:
      - "80:80"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: spug      
      DB_USER: spug
      DB_PASSWORD: spug
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - spug

networks:
  spug: